# This is a basic workflow to help you get started with Actions

name: Topaz for Total Test for demo

# Controls when the workflow will run
on:

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      name:
        # Host/IP adress input from users
        description: HCI Connection
        default: "CW13.bmc.com:16196"
        required: true
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    runs-on: windows-latest
    
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: git config --global core.longpaths true
      - name: Check HCI input value
        run: echo The HCI name is ${{ github.event.inputs.name }}
     
